import { Controller } from "@hotwired/stimulus";
import * as EpubJS from "epubjs";
import type { Book, Rendition } from "epubjs";

interface ProgressResponse {
  last_cfi?: string;
  bookmarks?: string[];
}

interface SaveProgressParams {
  cfi?: string;
  bookmarks?: string[];
}

interface SaveProgressPayload {
  last_cfi?: string;
  bookmarks?: string[];
}

interface ReaderDisplayedLocation {
  cfi?: string;
  displayed?: {
    page?: number;
    total?: number;
  };
}

type ReaderLocation =
  | { start?: ReaderDisplayedLocation }
  | ReaderDisplayedLocation
  | null
  | undefined;

interface PublisherPageList {
  pageFromCfi(cfi: string): number;
  lastPage?: number;
  pages?: unknown[];
  locations?: unknown[];
}

type EpubFactory = (urlOrData?: string | ArrayBuffer) => Book;

// Connects to data-controller="reader"
export default class extends Controller<HTMLElement> {
  static targets = [
    "stage",
    "prevButton",
    "nextButton",
    "pageStatus",
    "fontFamily",
    "fontSize",
    "fontSizeOutput",
    "spread",
  ];

  static values = {
    bookId: String,
    epubUrl: String,
    progressUrl: String,
    spread: { type: String, default: "none" },
  };

  // Target declarations (generated by Stimulus at runtime)
  declare readonly stageTarget: HTMLElement;
  declare readonly hasStageTarget: boolean;
  declare readonly prevButtonTarget: HTMLButtonElement;
  declare readonly nextButtonTarget: HTMLButtonElement;
  declare readonly pageStatusTarget: HTMLElement;
  declare readonly fontFamilyTarget: HTMLSelectElement;
  declare readonly fontSizeTarget: HTMLElement & {
    value?: string | number;
  };
  declare readonly fontSizeOutputTarget: HTMLOutputElement;
  declare readonly spreadTarget: HTMLSelectElement;

  // Value declarations (generated by Stimulus at runtime)
  declare bookIdValue: string;
  declare epubUrlValue: string;
  declare progressUrlValue: string;
  declare spreadValue: string;

  // Instance properties
  book: Book | null = null;
  rendition: Rendition | null = null;
  publisherPageList: PublisherPageList | null = null;
  totalBookPages: number | null = null;
  bookmarks: string[] = [];
  lastSavedCfi: string | null = null;
  pendingCfi: string | null = null;
  resizeTimer: ReturnType<typeof setTimeout> | null = null;
  saveProgressTimer: ReturnType<typeof setTimeout> | null = null;
  isInitializing: boolean = false;
  isRendering: boolean = false;
  locationGenId: number = 0;
  keyDownHandler!: (event: KeyboardEvent) => void;
  resizeHandler!: () => void;
  themeObserver: MutationObserver | null = null;

  private createBook(): Book {
    const factory = (EpubJS as unknown as { default: EpubFactory }).default;
    return factory();
  }

  private extractDisplayedLocation(
    location: ReaderLocation,
  ): ReaderDisplayedLocation | undefined {
    if (!location) return undefined;
    const maybeWrapped = location as { start?: ReaderDisplayedLocation };
    if (maybeWrapped.start) return maybeWrapped.start;
    return location as ReaderDisplayedLocation;
  }

  private extractCfi(location: ReaderLocation): string | undefined {
    return this.extractDisplayedLocation(location)?.cfi;
  }

  private currentFontSizeValue(): string {
    const rawValue =
      this.fontSizeTarget.value ??
      this.fontSizeTarget.getAttribute("value") ??
      "18";
    const normalized = String(rawValue).trim();
    const parsed = Number(normalized);
    if (Number.isFinite(parsed) && parsed > 0) {
      return String(parsed);
    }
    return "18";
  }

  private setFontSizeValue(nextValue: string): void {
    this.fontSizeTarget.value = nextValue;
    this.fontSizeTarget.setAttribute("value", nextValue);
  }

  connect() {
    // Prevent multiple initializations on the same element
    if ((this.element as any).__readerInitialized) {
      console.log("Reader already initialized on this element, skipping");
      return;
    }

    this.book = null;
    this.rendition = null;
    this.publisherPageList = null;
    this.totalBookPages = null;
    this.bookmarks = [];
    this.lastSavedCfi = null;
    this.pendingCfi = null;
    this.resizeTimer = null;
    this.saveProgressTimer = null;
    this.isInitializing = false;
    this.isRendering = false;
    this.locationGenId = 0;
    this.keyDownHandler = this.onKeydown.bind(this);
    this.resizeHandler = this.onResize.bind(this);
    this.startThemeObserver();

    console.log("Reader controller connected, stage dimensions:", {
      width: this.stageTarget?.clientWidth,
      height: this.stageTarget?.clientHeight,
    });

    // Mark as initializing to prevent duplicate init
    (this.element as any).__readerInitialized = true;

    // Defer initialization to ensure DOM is fully painted and sized
    setTimeout(() => {
      this.initialize();
    }, 100);
  }

  disconnect() {
    window.removeEventListener("keydown", this.keyDownHandler);
    window.removeEventListener("resize", this.resizeHandler);
    if (this.resizeTimer) clearTimeout(this.resizeTimer);
    if (this.saveProgressTimer) clearTimeout(this.saveProgressTimer);
    this.book = null;
    this.rendition = null;
    this.isRendering = false;
    this.locationGenId++;
    this.themeObserver?.disconnect();
    this.themeObserver = null;
  }

  private isDarkThemeActive(): boolean {
    return (
      document.documentElement.classList.contains("sl-theme-dark") ||
      document.body?.classList.contains("sl-theme-dark") ||
      false
    );
  }

  private startThemeObserver(): void {
    this.themeObserver?.disconnect();

    this.themeObserver = new MutationObserver(() => {
      this.applyTheme();
    });

    this.themeObserver.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class"],
    });

    if (document.body) {
      this.themeObserver.observe(document.body, {
        attributes: true,
        attributeFilter: ["class"],
      });
    }
  }

  getCsrfToken(): string {
    const meta = document.querySelector<HTMLMetaElement>(
      'meta[name="csrf-token"]',
    );
    return meta?.content ?? "";
  }

  async fetchEpubBinary(): Promise<ArrayBuffer> {
    const response = await fetch(this.epubUrlValue, {
      headers: {
        Accept: "application/epub+zip,*/*",
      },
      credentials: "same-origin",
    });

    if (!response.ok) {
      throw new Error(`EPUB request failed (${response.status})`);
    }

    return response.arrayBuffer();
  }

  async loadProgressFromDb(): Promise<string | null> {
    if (!this.progressUrlValue) return null;

    try {
      const response = await fetch(this.progressUrlValue, {
        headers: {
          Accept: "application/json",
        },
        credentials: "same-origin",
      });

      if (!response.ok) return null;

      const data = (await response.json()) as ProgressResponse;
      this.bookmarks = Array.isArray(data.bookmarks) ? data.bookmarks : [];
      this.lastSavedCfi = data.last_cfi ?? null;
      console.log("Loaded progress from DB:", { cfi: data.last_cfi });
      return data.last_cfi ?? null;
    } catch (error) {
      console.error("Error loading progress:", error);
      return null;
    }
  }

  async saveProgressToDb({
    cfi,
    bookmarks,
  }: SaveProgressParams = {}): Promise<void> {
    if (!this.progressUrlValue) return;

    const payload: SaveProgressPayload = {};
    if (typeof cfi === "string") payload.last_cfi = cfi;
    if (Array.isArray(bookmarks)) payload.bookmarks = bookmarks;
    if (Object.keys(payload).length === 0) return;

    console.log("Saving progress to DB:", { cfi: payload.last_cfi });

    try {
      await fetch(this.progressUrlValue, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
          "X-CSRF-Token": this.getCsrfToken(),
        },
        credentials: "same-origin",
        body: JSON.stringify(payload),
      });

      if (payload.last_cfi) {
        this.lastSavedCfi = payload.last_cfi;
        console.log("✓ Progress saved:", payload.last_cfi);
      }
    } catch (error) {
      console.error("✗ Save progress error:", error);
      // Ignore transient network failures; next relocation will retry.
    }
  }

  queueSaveCfi(cfi: string | null | undefined): void {
    if (!cfi || cfi === this.lastSavedCfi) return;
    this.pendingCfi = cfi;
    if (this.saveProgressTimer) clearTimeout(this.saveProgressTimer);

    this.saveProgressTimer = setTimeout(async () => {
      // Re-fetch the current location from the rendition to ensure we have the final state
      const currentLocation = await this.rendition?.currentLocation?.();
      const finalCfi = this.extractCfi(currentLocation);

      if (finalCfi && finalCfi !== this.lastSavedCfi) {
        this.saveProgressToDb({ cfi: finalCfi });
      }
      this.pendingCfi = null;
    }, 800);
  }

  updateStatus(location: ReaderLocation | null | undefined): void {
    const displayedLocation = this.extractDisplayedLocation(location);
    const displayed = displayedLocation?.displayed;
    const cfi = displayedLocation?.cfi;

    if (cfi) this.queueSaveCfi(cfi);

    const chapterText = displayed?.total
      ? `Chapter ${displayed.page}/${displayed.total}`
      : null;

    if (cfi && this.publisherPageList) {
      const publisherPage = this.publisherPageList.pageFromCfi(cfi);
      if (typeof publisherPage === "number" && publisherPage > 0) {
        const lastPublisherPage =
          this.publisherPageList.lastPage || publisherPage;
        this.pageStatusTarget.textContent = chapterText
          ? `Page ${publisherPage}/${lastPublisherPage} • ${chapterText}`
          : `Page ${publisherPage}/${lastPublisherPage}`;
        return;
      }
    }

    if (!cfi || !this.book?.locations || !this.totalBookPages) {
      this.pageStatusTarget.textContent = chapterText || "Reading";
      return;
    }

    const globalIndex = this.book.locations.locationFromCfi(cfi);
    if (typeof globalIndex !== "number" || globalIndex < 0) {
      this.pageStatusTarget.textContent = chapterText || "Reading";
      return;
    }

    const globalPage = globalIndex + 1;

    this.pageStatusTarget.textContent = chapterText
      ? `Page ${globalPage}/${this.totalBookPages} • ${chapterText}`
      : `Page ${globalPage}/${this.totalBookPages}`;
  }

  async generateBookLocations(): Promise<void> {
    if (!this.book) return;

    const genId = ++this.locationGenId;

    await this.book.ready;
    if (!this.book || this.locationGenId !== genId) return;

    if (this.book.loaded?.pageList) {
      await this.book.loaded.pageList;
      if (!this.book || this.locationGenId !== genId) return;
      const pageList = this.book.pageList as unknown as PublisherPageList;
      if (
        pageList &&
        Array.isArray(pageList.pages) &&
        pageList.pages.length > 0 &&
        Array.isArray(pageList.locations) &&
        pageList.locations.length > 0
      ) {
        this.publisherPageList = pageList;
      }
    }

    if (!this.book || this.locationGenId !== genId) return;
    try {
      await this.book.locations.generate(1024);
    } catch {
      return; // book was destroyed during generation
    }
    if (!this.book || this.locationGenId !== genId) return;
    this.totalBookPages = this.book.locations.length();

    const currentLocation = await this.rendition?.currentLocation?.();
    if (currentLocation) {
      this.updateStatus(currentLocation);
    }
  }

  async initialize() {
    // Prevent multiple concurrent initializations
    if (this.isInitializing) {
      console.log("Initialize already in progress, skipping");
      return;
    }
    this.isInitializing = true;
    this.isRendering = true;

    if (!this.hasStageTarget || !this.epubUrlValue) {
      this.pageStatusTarget.textContent = "Reader failed to initialize";
      console.error("Init checks failed:", {
        hasStageTarget: this.hasStageTarget,
        hasEpubUrl: !!this.epubUrlValue,
        stageTarget: this.stageTarget,
      });
      this.isInitializing = false;
      this.isRendering = false;
      return;
    }

    const FAMILY_KEY = "reader.fontFamily";
    const SIZE_KEY = "reader.fontSize";
    const SPREAD_KEY = "reader.spread";

    const savedFamily = localStorage.getItem(FAMILY_KEY);
    const savedSize = localStorage.getItem(SIZE_KEY);
    const savedSpread = localStorage.getItem(SPREAD_KEY);
    if (savedFamily) this.fontFamilyTarget.value = savedFamily;
    if (savedSize) this.setFontSizeValue(savedSize);
    if (savedSpread) this.spreadTarget.value = savedSpread;
    this.fontSizeOutputTarget.textContent = `${this.currentFontSizeValue()}px`;

    let epubBinary: ArrayBuffer;
    try {
      epubBinary = await this.fetchEpubBinary();
      console.log(
        "✓ EPUB binary fetched:",
        epubBinary?.byteLength || 0,
        "bytes",
      );
    } catch (error: unknown) {
      this.pageStatusTarget.textContent =
        error instanceof Error ? error.message : "Could not load EPUB file";
      console.error("✗ Fetch EPUB error:", error);
      this.isInitializing = false;
      this.isRendering = false;
      return;
    }

    this.book = null;

    // Clear the stage to prevent duplicate containers
    this.stageTarget.innerHTML = "";

    this.book = this.createBook();
    const book = this.book;

    try {
      await book.open(epubBinary, "binary");
      console.log("✓ EPUB book opened");
    } catch {
      this.pageStatusTarget.textContent = "Could not parse EPUB file";
      console.error("✗ Open EPUB error");
      this.isInitializing = false;
      this.isRendering = false;
      return;
    }

    try {
      this.rendition = book.renderTo(this.stageTarget, {
        width: "100%",
        height: "100%",
        flow: "paginated",
        spread: this.spreadTarget.value === "Double" ? "auto" : "none",
      });
      console.log("✓ Rendition created, rendered to stage");
    } catch (error: unknown) {
      this.pageStatusTarget.textContent = "Could not initialize reader";
      console.error("✗ RenderTo error:", error);
      this.isInitializing = false;
      this.isRendering = false;
      return;
    }

    this.rendition.on("relocated", (location: ReaderLocation) => {
      this.updateStatus(location);
    });

    const initialCfi = await this.loadProgressFromDb();
    try {
      console.log(
        "Attempting to display content, CFI:",
        initialCfi || "(start of book)",
      );
      await this.rendition.display(initialCfi || undefined);

      // Log the actual location after display
      const displayedLocation = await this.rendition?.currentLocation?.();
      const displayedCfi = this.extractCfi(displayedLocation);

      // If the displayed CFI doesn't match what we asked for, this EPUB has issues
      if (initialCfi && displayedCfi && initialCfi !== displayedCfi) {
        console.warn(
          "⚠ CFI mismatch detected - EPUB structure may be malformed",
          { requested: initialCfi, displayed: displayedCfi },
        );
      }

      console.log("✓ Content displayed", {
        savedCfi: initialCfi,
        displayedCfi: displayedCfi,
        stage: this.stageTarget.innerHTML.length,
      });

      // Apply font styles after content is rendered
      this.applyTheme();
      console.log("✓ Theme applied");

      // Force layout recalculation after content has been rendered
      this.rendition.resize(
        this.stageTarget.clientWidth,
        this.stageTarget.clientHeight,
      );
      console.log(
        "✓ Layout resized to",
        this.stageTarget.clientWidth,
        "x",
        this.stageTarget.clientHeight,
      );

      // Generate locations asynchronously in background
      this.generateBookLocations();
    } catch (error: unknown) {
      this.pageStatusTarget.textContent = "Could not display this book";
      console.error("✗ Reader display error:", error);
      console.error("Stage target info:", {
        hasTarget: !!this.stageTarget,
        innerHTML: this.stageTarget?.innerHTML?.substring(0, 200),
        clientWidth: this.stageTarget?.clientWidth,
        clientHeight: this.stageTarget?.clientHeight,
      });
    }

    window.addEventListener("keydown", this.keyDownHandler);
    window.addEventListener("resize", this.resizeHandler);
    this.isInitializing = false;
    this.isRendering = false;
    console.log("✓ Reader initialization complete");
  }

  applyTheme() {
    if (!this.rendition) return;

    const isDark = this.isDarkThemeActive();

    this.rendition.themes.register("librestack-light", {
      body: {
        background: "#ffffff",
        color: "#111827",
        "font-family": this.fontFamilyTarget.value,
        "font-size": `${this.currentFontSizeValue()}px`,
        "line-height": "1.5",
      },
      a: {
        color: "#1d4ed8",
      },
    });

    this.rendition.themes.register("librestack-dark", {
      body: {
        background: "#0f1115",
        color: "#e5e7eb",
        "font-family": this.fontFamilyTarget.value,
        "font-size": `${this.currentFontSizeValue()}px`,
        "line-height": "1.5",
      },
      a: {
        color: "#93c5fd",
      },
    });

    this.rendition.themes.select(
      isDark ? "librestack-dark" : "librestack-light",
    );

    // In paginated flow, avoid body-level constraints that can interfere
    // with page column calculations. Focus on font controls only.
    // Ensure dynamic control updates are applied immediately in the rendered spine.
    this.rendition.themes.override("font-family", this.fontFamilyTarget.value);
    this.rendition.themes.fontSize(`${this.currentFontSizeValue()}px`);
  }

  prev(event: Event): void {
    event.preventDefault();
    const rendition = this.rendition;
    if (!rendition || this.isRendering || this.isInitializing) return;
    rendition.prev().catch((error: unknown) => {
      console.warn("Ignored prev navigation error", error);
    });
  }

  next(event: Event): void {
    event.preventDefault();
    const rendition = this.rendition;
    if (!rendition || this.isRendering || this.isInitializing) return;
    rendition.next().catch((error: unknown) => {
      console.warn("Ignored next navigation error", error);
    });
  }

  fontFamilyChanged() {
    localStorage.setItem("reader.fontFamily", this.fontFamilyTarget.value);
    if (this.rendition) {
      this.rendition.themes.override(
        "font-family",
        this.fontFamilyTarget.value,
      );
    }
    this.applyTheme();
  }

  fontSizeChanged() {
    const size = this.currentFontSizeValue();
    this.setFontSizeValue(size);
    this.fontSizeOutputTarget.textContent = `${size}px`;
    localStorage.setItem("reader.fontSize", size);
    if (this.rendition) {
      this.rendition.themes.fontSize(`${size}px`);
    }
    this.applyTheme();
  }

  onKeydown(event: KeyboardEvent): void {
    const rendition = this.rendition;
    if (!rendition || this.isRendering || this.isInitializing) return;

    if (event.key === "ArrowLeft") {
      event.preventDefault();
      rendition.prev().catch((error: unknown) => {
        console.warn("Ignored ArrowLeft navigation error", error);
      });
    } else if (event.key === "ArrowRight") {
      event.preventDefault();
      rendition.next().catch((error: unknown) => {
        console.warn("Ignored ArrowRight navigation error", error);
      });
    }
  }

  onResize(): void {
    if (this.resizeTimer) clearTimeout(this.resizeTimer);
    this.resizeTimer = setTimeout(() => {
      this.rendition?.resize(
        this.stageTarget.clientWidth,
        this.stageTarget.clientHeight,
      );
    }, 150);
  }

  async spreadChanged(): Promise<void> {
    const newSpread = this.spreadTarget.value;
    localStorage.setItem("reader.spread", newSpread);
    this.spreadValue = newSpread;
    if (this.rendition) {
      this.rendition.spread(this.spreadValue === "Double" ? "auto" : "none");
      // const cfi = this.extractCfi(currentLocation);
      // await this.reRender(cfi);
    }
  }
}
