// <auto-generated />
using Librestack.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace libreStack.Migrations
{
    [DbContext(typeof(LibrestackDbContext))]
    [Migration("20260528200622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Librestack.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AmazonId")
                        .HasColumnType("text")
                        .HasColumnName("amazon_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isbn");

                    b.Property<string>("LCCN")
                        .HasColumnType("text")
                        .HasColumnName("lccn");

                    b.Property<string>("OCLCWorldCat")
                        .HasColumnType("text")
                        .HasColumnName("oclc_world_cat");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<int>("SeriesOrder")
                        .HasColumnType("integer")
                        .HasColumnName("series_order");

                    b.Property<string>("SeriesTitle")
                        .HasColumnType("text")
                        .HasColumnName("series_title");

                    b.Property<int>("SeriesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("series_total");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("WorkId")
                        .HasColumnType("text")
                        .HasColumnName("work_id");

                    b.Property<string>("epubPath")
                        .HasColumnType("text")
                        .HasColumnName("epub_path");

                    b.HasKey("Id")
                        .HasName("pk_library");

                    b.ToTable("library", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.LibraryTags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_library_tags");

                    b.ToTable("library_tags", (string)null);
                });

            modelBuilder.Entity("applied_library_tags", b =>
                {
                    b.Property<int>("library_id")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.Property<int>("tag_id")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("library_id", "tag_id")
                        .HasName("pk_applied_library_tags");

                    b.HasIndex("tag_id")
                        .HasDatabaseName("ix_applied_library_tags_tag_id");

                    b.ToTable("applied_library_tags", (string)null);
                });

            modelBuilder.Entity("applied_library_tags", b =>
                {
                    b.HasOne("Librestack.Models.Library", null)
                        .WithMany()
                        .HasForeignKey("library_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applied_library_tags_library_library_id");

                    b.HasOne("Librestack.Models.LibraryTags", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applied_library_tags_library_tags_tag_id");
                });
#pragma warning restore 612, 618
        }
    }
}
