// <auto-generated />
using System;
using Librestack.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace libreStack.Migrations
{
    [DbContext(typeof(LibrestackDbContext))]
    [Migration("20260805194100_caseFix")]
    partial class caseFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Librestack.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("collection_id");

                    b.Property<string>("CoverContentType")
                        .HasColumnType("text")
                        .HasColumnName("cover_content_type");

                    b.Property<byte[]>("CoverImage")
                        .HasColumnType("bytea")
                        .HasColumnName("cover_image");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EpubPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("epub_path");

                    b.Property<string>("ISBN")
                        .HasColumnType("text")
                        .HasColumnName("isbn");

                    b.Property<string>("ISBN13")
                        .HasColumnType("text")
                        .HasColumnName("isbn13");

                    b.Property<string>("LCCN")
                        .HasColumnType("text")
                        .HasColumnName("lccn");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("OCLCWorldCat")
                        .HasColumnType("text")
                        .HasColumnName("oclc_world_cat");

                    b.Property<string>("OpenLibraryAuthorId")
                        .HasColumnType("text")
                        .HasColumnName("open_library_author_id");

                    b.Property<string>("OpenLibraryCoverId")
                        .HasColumnType("text")
                        .HasColumnName("open_library_cover_id");

                    b.Property<string>("OpenLibraryEditionId")
                        .HasColumnType("text")
                        .HasColumnName("open_library_edition_id");

                    b.Property<DateTime?>("OpenLibraryMetadataLastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_library_metadata_last_updated");

                    b.Property<string>("OpenLibraryWorkId")
                        .HasColumnType("text")
                        .HasColumnName("open_library_work_id");

                    b.Property<string>("PublishDate")
                        .HasColumnType("text")
                        .HasColumnName("publish_date");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<int?>("SeriesOrder")
                        .HasColumnType("integer")
                        .HasColumnName("series_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("WikidataId")
                        .HasColumnType("text")
                        .HasColumnName("wikidata_id");

                    b.Property<DateTime?>("WikidataMetaLastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("wikidata_meta_last_updated");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_books_series_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_books_user_id");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.BookTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_book_tags");

                    b.ToTable("book_tags", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.BookmarkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<string>("CfiLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cfi_location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookmarks");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_bookmarks_book_id");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("library_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_libraries");

                    b.ToTable("libraries", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.LibreStackConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDeleteFromDisk")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_delete_from_disk");

                    b.Property<bool>("AllowLibraryUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_library_updates");

                    b.Property<bool>("AllowNewLibraries")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_new_libraries");

                    b.Property<bool>("AllowNewUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_new_users");

                    b.Property<bool>("AllowRemoveBooksFromLibrary")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_remove_books_from_library");

                    b.Property<bool>("AllowUploadToLibrary")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_upload_to_library");

                    b.Property<bool>("AttemptSeriesParsing")
                        .HasColumnType("boolean")
                        .HasColumnName("attempt_series_parsing");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_setup_complete");

                    b.Property<int>("LibraryScanInterval")
                        .HasColumnType("integer")
                        .HasColumnName("library_scan_interval");

                    b.Property<bool>("ScanLibrariesService")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_libraries_service");

                    b.HasKey("Id")
                        .HasName("pk_libre_stack_config");

                    b.ToTable("libre_stack_config", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.ReadingProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<string>("CfiLocation")
                        .HasColumnType("text")
                        .HasColumnName("cfi_location");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<DateTime?>("LastRead")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reading_progress");

                    b.HasIndex("BookId")
                        .IsUnique()
                        .HasDatabaseName("ix_reading_progress_book_id");

                    b.ToTable("reading_progress", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_token");

                    b.Property<string>("ReplacedByHash")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_hash");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("SeriesImage")
                        .HasColumnType("bytea")
                        .HasColumnName("series_image");

                    b.Property<string>("SeriesTitle")
                        .HasColumnType("text")
                        .HasColumnName("series_title");

                    b.Property<int>("SeriesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("series_total");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("UserId", "SeriesTitle")
                        .IsUnique()
                        .HasDatabaseName("ix_series_user_id_series_title");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoverHeight")
                        .HasColumnType("integer")
                        .HasColumnName("cover_height");

                    b.Property<int>("CoverWidth")
                        .HasColumnType("integer")
                        .HasColumnName("cover_width");

                    b.Property<bool>("GroupByCollections")
                        .HasColumnType("boolean")
                        .HasColumnName("group_by_collections");

                    b.Property<bool>("GroupBySeries")
                        .HasColumnType("boolean")
                        .HasColumnName("group_by_series");

                    b.Property<int>("LastSelectedLibrary")
                        .HasColumnType("integer")
                        .HasColumnName("last_selected_library");

                    b.Property<string>("LibraryBase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("library_base");

                    b.Property<double>("LineHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("line_height");

                    b.Property<string>("ReadingFontLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading_font_label");

                    b.Property<int>("ReadingFontSize")
                        .HasColumnType("integer")
                        .HasColumnName("reading_font_size");

                    b.Property<string>("ReadingFontValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading_font_value");

                    b.Property<string>("ReadingTheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading_theme");

                    b.Property<bool>("ShowAuthors")
                        .HasColumnType("boolean")
                        .HasColumnName("show_authors");

                    b.Property<bool>("ShowCollections")
                        .HasColumnType("boolean")
                        .HasColumnName("show_collections");

                    b.Property<bool>("ShowCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("show_completed");

                    b.Property<bool>("ShowDescriptionOnHover")
                        .HasColumnType("boolean")
                        .HasColumnName("show_description_on_hover");

                    b.Property<bool>("ShowLibraryAsHome")
                        .HasColumnType("boolean")
                        .HasColumnName("show_library_as_home");

                    b.Property<bool>("ShowSeries")
                        .HasColumnType("boolean")
                        .HasColumnName("show_series");

                    b.Property<bool>("ShowTitles")
                        .HasColumnType("boolean")
                        .HasColumnName("show_titles");

                    b.Property<bool>("SortAscending")
                        .HasColumnType("boolean")
                        .HasColumnName("sort_ascending");

                    b.Property<string>("SortBy")
                        .HasColumnType("text")
                        .HasColumnName("sort_by");

                    b.Property<string>("Spread")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spread");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_settings");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_settings_user_id");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("applied_book_tags", b =>
                {
                    b.Property<int>("book_id")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("tag_id")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("book_id", "tag_id")
                        .HasName("pk_applied_book_tags");

                    b.HasIndex("tag_id")
                        .HasDatabaseName("ix_applied_book_tags_tag_id");

                    b.ToTable("applied_book_tags", (string)null);
                });

            modelBuilder.Entity("library_books", b =>
                {
                    b.Property<int>("book_id")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("library_id")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.HasKey("book_id", "library_id")
                        .HasName("pk_library_books");

                    b.HasIndex("library_id")
                        .HasDatabaseName("ix_library_books_library_id");

                    b.ToTable("library_books", (string)null);
                });

            modelBuilder.Entity("Librestack.Models.Book", b =>
                {
                    b.HasOne("Librestack.Models.Series", "Series")
                        .WithMany("Books")
                        .HasForeignKey("SeriesId")
                        .HasConstraintName("fk_books_series_series_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_users_user_id");

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Librestack.Models.BookmarkModel", b =>
                {
                    b.HasOne("Librestack.Models.Book", null)
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_books_book_id");
                });

            modelBuilder.Entity("Librestack.Models.ReadingProgress", b =>
                {
                    b.HasOne("Librestack.Models.Book", null)
                        .WithOne("ReadingProgress")
                        .HasForeignKey("Librestack.Models.ReadingProgress", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_progress_books_book_id");
                });

            modelBuilder.Entity("Librestack.Models.UserSettings", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("Librestack.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("applied_book_tags", b =>
                {
                    b.HasOne("Librestack.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applied_book_tags_books_book_id");

                    b.HasOne("Librestack.Models.BookTag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applied_book_tags_book_tags_tag_id");
                });

            modelBuilder.Entity("library_books", b =>
                {
                    b.HasOne("Librestack.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_library_books_books_book_id");

                    b.HasOne("Librestack.Models.Library", null)
                        .WithMany()
                        .HasForeignKey("library_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_library_books_libraries_library_id");
                });

            modelBuilder.Entity("Librestack.Models.Book", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("ReadingProgress");
                });

            modelBuilder.Entity("Librestack.Models.Series", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
